### ISSUE TITLE
Add Accounts

### ISSUE THREAD

**Issue by mockir0** [alekthegenius/Woof#1]
**Is your feature request related to a problem? Please describe.**
I want to make an account

**Describe the solution you'd like**
Add the feature to make accounts

**Comment by alekthegenius** [comment]
For the time being, I am using GitHub Pages to deploy the website and build the UI. GitHub-Pages only supports static sites, meaning it can only render what is in the HTML code, and there is no user interaction. While static sites are the ideal choice for blogs and portfolios, they have their limitations when creating a website that requires multiple users, databases, and user interaction. That is why I will use AWS (Amazon Web Services) to deploy the Woof and use python to handle the accounts once finished with the UI.
